alter table INTERSHIP_PURCHASE add constraint FK_INTERSHIP_PURCHASE_ON_STORE foreign key (STORE_ID) references INTERSHIP_STORE(ID);
alter table INTERSHIP_PURCHASE add constraint FK_INTERSHIP_PURCHASE_ON_CUSTOMER foreign key (CUSTOMER_ID) references INTERSHIP_CUSTOMER(ID);
create unique index IDX_INTERSHIP_PURCHASE_UK_ORDER_NUMBER on INTERSHIP_PURCHASE (ORDER_NUMBER) where DELETE_TS is null ;
create index IDX_INTERSHIP_PURCHASE_ON_STORE on INTERSHIP_PURCHASE (STORE_ID);
create index IDX_INTERSHIP_PURCHASE_ON_CUSTOMER on INTERSHIP_PURCHASE (CUSTOMER_ID);
