-- begin INTERSHIP_STORE
alter table INTERSHIP_STORE add constraint FK_INTERSHIP_STORE_ON_TRADE_NETWORK foreign key (TRADE_NETWORK_ID) references INTERSHIP_TRADE_NETWORK(ID)^
create unique index IDX_INTERSHIP_STORE_UK_NUMBER_ on INTERSHIP_STORE (NUMBER_) where DELETE_TS is null ^
create index IDX_INTERSHIP_STORE_ON_TRADE_NETWORK on INTERSHIP_STORE (TRADE_NETWORK_ID)^
-- end INTERSHIP_STORE
-- begin INTERSHIP_TRADE_NETWORK
create unique index IDX_INTERSHIP_TRADE_NETWORK_UK_NAME on INTERSHIP_TRADE_NETWORK (NAME) where DELETE_TS is null ^
-- end INTERSHIP_TRADE_NETWORK
-- begin INTERSHIP_PRICE_HISTORY
alter table INTERSHIP_PRICE_HISTORY add constraint FK_INTERSHIP_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references INTERSHIP_PRODUCT_IN_STORE(ID)^
alter table INTERSHIP_PRICE_HISTORY add constraint FK_INTERSHIP_PRICE_HISTORY_ON_STORE foreign key (STORE_ID) references INTERSHIP_STORE(ID)^
create index IDX_INTERSHIP_PRICE_HISTORY_ON_PRODUCT on INTERSHIP_PRICE_HISTORY (PRODUCT_ID)^
create index IDX_INTERSHIP_PRICE_HISTORY_ON_STORE on INTERSHIP_PRICE_HISTORY (STORE_ID)^
-- end INTERSHIP_PRICE_HISTORY
-- begin INTERSHIP_PRODUCT_MANUFACTURER
alter table INTERSHIP_PRODUCT_MANUFACTURER add constraint FK_INTERSHIP_PRODUCT_MANUFACTURER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_INTERSHIP_PRODUCT_MANUFACTURER_UK_NAME on INTERSHIP_PRODUCT_MANUFACTURER (NAME) where DELETE_TS is null ^
create index IDX_INTERSHIP_PRODUCT_MANUFACTURER_ON_USER on INTERSHIP_PRODUCT_MANUFACTURER (USER_ID)^
-- end INTERSHIP_PRODUCT_MANUFACTURER
-- begin INTERSHIP_PRODUCT
alter table INTERSHIP_PRODUCT add constraint FK_INTERSHIP_PRODUCT_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references INTERSHIP_PRODUCT_MANUFACTURER(ID)^
create unique index IDX_INTERSHIP_PRODUCT_UK_NAME on INTERSHIP_PRODUCT (NAME) where DELETE_TS is null ^
create index IDX_INTERSHIP_PRODUCT_ON_MANUFACTURER on INTERSHIP_PRODUCT (MANUFACTURER_ID)^
-- end INTERSHIP_PRODUCT
-- begin INTERSHIP_PRODUCT_IN_PURCHASE
alter table INTERSHIP_PRODUCT_IN_PURCHASE add constraint FK_INTERSHIP_PRODUCT_IN_PURCHASE_ON_PURCHASE foreign key (PURCHASE_ID) references INTERSHIP_PURCHASE(ID)^
alter table INTERSHIP_PRODUCT_IN_PURCHASE add constraint FK_INTERSHIP_PRODUCT_IN_PURCHASE_ON_PRODUCT foreign key (PRODUCT_ID) references INTERSHIP_PRODUCT_IN_STORE(ID)^
create index IDX_INTERSHIP_PRODUCT_IN_PURCHASE_ON_PURCHASE on INTERSHIP_PRODUCT_IN_PURCHASE (PURCHASE_ID)^
create index IDX_INTERSHIP_PRODUCT_IN_PURCHASE_ON_PRODUCT on INTERSHIP_PRODUCT_IN_PURCHASE (PRODUCT_ID)^
-- end INTERSHIP_PRODUCT_IN_PURCHASE
-- begin INTERSHIP_PRODUCT_IN_STORE
alter table INTERSHIP_PRODUCT_IN_STORE add constraint FK_INTERSHIP_PRODUCT_IN_STORE_ON_PRODUCT foreign key (PRODUCT_ID) references INTERSHIP_PRODUCT(ID)^
alter table INTERSHIP_PRODUCT_IN_STORE add constraint FK_INTERSHIP_PRODUCT_IN_STORE_ON_STORE foreign key (STORE_ID) references INTERSHIP_STORE(ID)^
create index IDX_INTERSHIP_PRODUCT_IN_STORE_ON_PRODUCT on INTERSHIP_PRODUCT_IN_STORE (PRODUCT_ID)^
create index IDX_INTERSHIP_PRODUCT_IN_STORE_ON_STORE on INTERSHIP_PRODUCT_IN_STORE (STORE_ID)^
-- end INTERSHIP_PRODUCT_IN_STORE
-- begin INTERSHIP_CUSTOMER
create unique index IDX_INTERSHIP_CUSTOMER_UK_EMAIL on INTERSHIP_CUSTOMER (EMAIL) where DELETE_TS is null ^
-- end INTERSHIP_CUSTOMER
-- begin INTERSHIP_PURCHASE
alter table INTERSHIP_PURCHASE add constraint FK_INTERSHIP_PURCHASE_ON_STORE foreign key (STORE_ID) references INTERSHIP_STORE(ID)^
alter table INTERSHIP_PURCHASE add constraint FK_INTERSHIP_PURCHASE_ON_CUSTOMER foreign key (CUSTOMER_ID) references INTERSHIP_CUSTOMER(ID)^
create unique index IDX_INTERSHIP_PURCHASE_UK_ORDER_NUMBER on INTERSHIP_PURCHASE (ORDER_NUMBER) where DELETE_TS is null ^
create index IDX_INTERSHIP_PURCHASE_ON_STORE on INTERSHIP_PURCHASE (STORE_ID)^
create index IDX_INTERSHIP_PURCHASE_ON_CUSTOMER on INTERSHIP_PURCHASE (CUSTOMER_ID)^
-- end INTERSHIP_PURCHASE
-- begin INTERSHIP_INDIVIDUALCUSTOMER
alter table intership_IndividualCustomer add constraint FK_INTERSHIP_INDIVIDUALCUSTOMER_ON_ID foreign key (ID) references INTERSHIP_CUSTOMER(ID) on delete CASCADE^
-- end INTERSHIP_INDIVIDUALCUSTOMER
-- begin INTERSHIP_LEGALENTITYCUSTOMER
alter table intership_LegalEntityCustomer add constraint FK_INTERSHIP_LEGALENTITYCUSTOMER_ON_ID foreign key (ID) references INTERSHIP_CUSTOMER(ID) on delete CASCADE^
-- end INTERSHIP_LEGALENTITYCUSTOMER
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_CUSTOMER foreign key (CUSTOMER_ID) references INTERSHIP_CUSTOMER(ID)^
create index IDX_SEC_USER_ON_CUSTOMER on SEC_USER (CUSTOMER_ID)^
-- end SEC_USER
